# Generated by Django 3.2.6 on 2021-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20210924_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('정보', '정보게시판'), ('자랑', '자랑게시판'), ('챌린지', '챌린지')], max_length=20),
        ),
    ]
