# Generated by Django 3.2.6 on 2021-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20210924_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('정보', '정보게시판'), ('자랑', '자랑게시판')], max_length=20, unique=True),
        ),
    ]
