# Generated by Django 3.2.6 on 2021-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundapp', '0002_alter_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to='background/'),
        ),
    ]
