# Generated by Django 3.2.6 on 2021-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundapp', '0003_alter_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_dot/')),
                ('price', models.IntegerField(default=15)),
            ],
        ),
    ]
