# Generated by Django 3.2.6 on 2021-08-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundapp', '0004_background_dot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background_Dot',
        ),
    ]
