# Generated by Django 3.2.6 on 2021-08-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundapp', '0005_delete_background_dot'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='state',
            field=models.CharField(default='unsold', max_length=10),
        ),
    ]
