# Generated by Django 3.2.6 on 2021-08-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challengeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(null=True, upload_to='challenge/'),
        ),
    ]
