# Generated by Django 3.2.6 on 2021-08-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengeapp', '0002_auto_20210831_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='user',
            new_name='writer',
        ),
    ]
