# Generated by Django 3.2.6 on 2021-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeapp', '0004_alter_challenge_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenge/'),
        ),
    ]
