# Generated by Django 3.2.6 on 2021-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeapp', '0005_auto_20210907_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
