# Generated by Django 3.2.6 on 2021-09-07 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challengeapp', '0006_challenge_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='writer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
