# Generated by Django 3.2.6 on 2021-09-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeapp', '0007_alter_challenge_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(choices=[('의약 폐기물 분리수거하기', '의약 폐기물 분리수거하기'), ('음식 남기지 않기', '음식 남기지 않기'), ('업사이클 브랜드 제품 사용하기', '업사이클 브랜드 제품 사용하기'), ('중고마켓에서 물건 사고 팔기', '중고마켓에서 물건 사고 팔기'), ('녹색제품 이용하기', '녹색제품 이용하기')], max_length=200, null=True),
        ),
    ]
