# Generated by Django 3.2.6 on 2021-09-24 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challengeapp', '0008_alter_challenge_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(null=True, upload_to='challenge/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
